### ISSUE TITLE
Lines in raster after importing from Database

### ISSUE THREAD

**Issue by BernoGreyling** [mablab/rpostgis#19]
Hi,

I have a large dem stored on a remote DB and when importing with pgGetRast, lines appear on seamingly random locations :

![image](https://user-images.githubusercontent.com/14345568/67685717-4a682900-f99e-11e9-801f-1206a0b3b5f0.png)

When using QGIS or the readGDAL function in R, there are no issues. Any idea where this could be originating from? When importing smaller dems, there are no such artifacts.

Thanks!

**Comment by dnbucklin** [comment]
If you use the `boundary` argument in `pgGetRast` to subset what you're loading into R, do you still see these lines, in the same locations?

Also can you tell what raster value is being applied to these lines? It appears they are not NA(?)

**Comment by BernoGreyling** [comment]
Hey @dnbucklin 

Here I selected 2 different boundaries. It seems as though the lines stay in the same place
![image](https://user-images.githubusercontent.com/14345568/67751621-1f331780-fa3a-11e9-8807-d172f5667e9b.png)

![image](https://user-images.githubusercontent.com/14345568/67751648-2b1ed980-fa3a-11e9-87cb-127614478008.png)

And then when I pull the DEM from the DB into QGIS

![image](https://user-images.githubusercontent.com/14345568/67751918-a97b7b80-fa3a-11e9-9c64-a1460c9e591a.png)

The lines have a value of 0 as shown below. The screenshot doesnt show the mouse ofcourse but it is hovering over the line: 
![image](https://user-images.githubusercontent.com/14345568/67752008-d596fc80-fa3a-11e9-9244-ed11efe908f9.png)


Thanks!

**Comment by dnbucklin** [comment]
Thanks @BernoGreyling ; these lines look like they could be along raster tile boundaries. If that's the case, and you pull just one of the problem tiles with from the raster with `pgGetRast` (use `clauses` to select one row), do you still see this stripe along an edge?

Also, are the raster properties (origin, resolution, extent, dimensions) in the imported R raster as expected (i.e. same as in PostGIS/QGIS)?

**Comment by BernoGreyling** [comment]
Hi @dnbucklin ,

It seems that almost all the tiles have these lines if I pull them row by row. And as far as I check, always at the bottom right. The rest of the properties come out perfectly, so no issues with that.

![image](https://user-images.githubusercontent.com/14345568/67949117-cc02c580-fbef-11e9-9ed8-0eca1adc3a74.png)

Thanks!

**Comment by dnbucklin** [comment]
Hmm, if the extent/dimensions match the tile in PostGIS, those data might actually be in the PostGIS raster. Possibly they're supposed to be nodata, and they're not getting imported correctly. You should be able to tell if that's the case with this query for one of those tiles:

```
select st_summary(rast), st_bandnodatavalue(rast) nodata_value, 
st_count(rast, 1, true) data_pixels, st_count(rast, 1, false) all_pixels, 
ST_ValueCount(rast,1,0) zero_value_pixels from 
{schema.table} where rid = {XX};
```

**Comment by bernorev** [comment]
Running the query above gives the following :

![image](https://user-images.githubusercontent.com/57282983/68116543-c238d500-ff03-11e9-8465-caddc24596fd.png)

**Comment by BernoGreyling** [comment]
Running the command above I get the following:

![image](https://user-images.githubusercontent.com/14345568/68116656-0f1cab80-ff04-11e9-9460-440c1019ba01.png)

**Comment by dnbucklin** [comment]
Based on this information, it looks like the zero values are also in the PostGIS raster, and the `pgGetRast` is performing as expected. It may be the case that those values are in overlap areas between tiles, but if they are not marked as nodata, they will not be ignored on import. 

To get these rasters to import correctly with `pgGetRast` may require reclassifying those values as nodata in the PostGIS raster, and/or re-importing the raster so the extra line is not there in the first place.
